In [69]:
import pandas as pd
import numpy as np

# Загрузка и подготовка данных

In [70]:
#импортируем подготовленный датасет
pokemon_df = pd.read_csv('../data/pokemon_preprocessed.csv')

In [71]:
#убеждаемся, что загрузка прошла успешно
pokemon_df.head()

Type 1  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Legendary  \
0  Grass    318  45      49       49       65       65     45          0   
1  Grass    405  60      62       63       80       80     60          0   
2  Grass    525  80      82       83      100      100     80          0   
3  Grass    625  80     100      123      122      120     80          0   
4   Fire    309  39      52       43       60       50     65          0   

   gen_1  gen_2  gen_3  gen_4  gen_5  gen_6  
0      1      0      0      0      0      0  
1      1      0      0      0      0      0  
2      1      0      0      0      0      0  
3      1      0      0      0      0      0  
4      1      0      0      0      0      0

In [72]:
#выведем весь список типов у покемонов
pokemon_df['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [73]:
#создадим вектора X и y
X_with_total = pokemon_df.iloc[:, 1:].values
X = pokemon_df.iloc[:, 1:8].values
y = pokemon_df.iloc[:, 0:1].values
print(y)

[['Grass']
 ['Grass']
 ['Grass']
 ['Grass']
 ['Fire']
 ['Fire']
 ['Fire']
 ['Fire']
 ['Fire']
 ['Water']
 ['Water']
 ['Water']
 ['Water']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Normal']
 ['Poison']
 ['Poison']
 ['Electric']
 ['Electric']
 ['Ground']
 ['Ground']
 ['Poison']
 ['Poison']
 ['Poison']
 ['Poison']
 ['Poison']
 ['Poison']
 ['Fairy']
 ['Fairy']
 ['Fire']
 ['Fire']
 ['Normal']
 ['Normal']
 ['Poison']
 ['Poison']
 ['Grass']
 ['Grass']
 ['Grass']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Bug']
 ['Ground']
 ['Ground']
 ['Normal']
 ['Normal']
 ['Water']
 ['Water']
 ['Fighting']
 ['Fighting']
 ['Fire']
 ['Fire']
 ['Water']
 ['Water']
 ['Water']
 ['Psychic']
 ['Psychic']
 ['Psychic']
 ['Psychic']
 ['Fighting']
 ['Fighting']
 ['Fighting']
 ['Grass']
 ['Grass']
 ['Grass']
 ['Water']
 ['Water']
 ['Rock']
 ['Rock']
 ['Rock']
 ['Fire']
 ['Fire']
 ['Water']
 ['Water']
 ['Water']
 ['Electric']

In [74]:
from sklearn.model_selection import train_test_split
#для начала будем обучать без признака Total
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [75]:
from sklearn.preprocessing import StandardScaler

#разбиваем данные на вещественные и бинарные (сюда так же входит порядковый признак, закодированный one-hot)

# X_train_without_bin = X_train[:, :6]
# X_test_without_bin = X_test[:, :6]
# X_train_bin = X_train[:, 6:]
# X_test_bin = X_test[:, 6:]

#обучаем скейлер на обучающей выборке только с вещественными признаками

scaler = StandardScaler()
# scaler.fit(X_train_without_bin)
scaler.fit(X_train)

#нормируем вещественные признаки обучающей и тестовой выборок

# X_train_without_bin = scaler.transform(X_train_without_bin)
# X_test_without_bin = scaler.transform(X_test_without_bin)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#объединяем их обратно

# temp_1 = []
# temp_2 = []

# for i in range(len(X_train_without_bin)):
#     temp_1.append(np.concatenate((X_train_without_bin[i], X_train_bin[i])))
#     if i < len(X_test_without_bin):
#         temp_2.append(np.concatenate((X_test_without_bin[i], X_test_bin[i])))
    
# X_train = np.array(temp_1)
# X_test = np.array(temp_2)

# Метод k-ближайших соседей (K-Nearest Neighbors)

In [76]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)

x:\programs\python\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [77]:
from sklearn.metrics import classification_report, confusion_matrix

y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 6  0  0  0  0  0  0  0  0  2  0  0  2  0  0  0  0  0]
 [ 0  2  1  1  0  0  1  0  0  0  0  0  0  0  0  0  0  2]
 [ 0  0  1  0  1  0  1  0  0  0  0  0  0  0  0  1  0  2]
 [ 0  1  0  4  0  0  1  0  0  0  0  0  0  0  0  0  0  3]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  1  0  0  0  0  2]
 [ 0  0  0  0  0  0  0  0  0  1  1  1  3  0  0  0  0  0]
 [ 0  0  1  0  0  0  2  0  0  0  1  0  1  0  1  0  0  3]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  0  1  0  0  1  0  1  1  0  0  0  0  0  0  0  0]
 [ 3  1  0  1  2  0  5  0  0  0  0  0  1  0  0  0  1  1]
 [ 1  0  1  0  0  2  1  0  2  0  1  0  2  0  0  2  0  0]
 [ 1  0  0  2  0  0  2  0  0  1  0  0  0  0  0  0  0  2]
 [ 4  0  0  1  0  0  1  0  0  2  0  0 10  0  0  1  0  2]
 [ 0  0  1  0  0  0  0  0  1  1  0  0  1  0  0  0  0  0]
 [ 2  1  1  3  0  0  1  0  1  1  0  0  0  0  0  0  0  3]
 [ 2  0  0  0  0  0  0  0  0  0  0  0  1  0  0  1  0  2]
 [ 4  0  2  0  0  0  0  0  0  0  0  0  0  0  1  1  1  0]
 [ 0  1  1  0  1  0  0  0  1  2

x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Классификатор дерева решений (Decision Tree Classifier)

In [78]:
from sklearn import tree

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [79]:
y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[4 0 0 1 1 0 0 0 0 0 0 0 2 1 1 0 0 0]
 [2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 3]
 [0 2 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0]
 [1 0 1 4 0 0 0 0 0 0 0 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 0 0 2 0 0 3 1 0 0 0 0]
 [0 0 0 2 0 0 2 0 1 2 0 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 2 0 0 0 0 0 1 0 0 1]
 [0 1 0 0 2 0 2 0 0 0 0 2 2 1 0 0 1 4]
 [1 1 1 1 0 1 1 0 0 0 2 0 2 0 0 1 0 1]
 [0 0 0 1 1 0 0 0 0 0 0 0 2 0 1 0 0 3]
 [1 1 1 0 0 0 1 0 0 2 0 0 7 2 0 3 0 3]
 [1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 1 4 0 0 0 0 1 0 0 1 0 0 3 1 0 2]
 [0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 1]
 [1 0 1 0 0 0 0 0 2 1 0 0 1 0 0 2 0 1]
 [0 2 0 1 2 1 0 0 1 3 0 1 2 1 0 0 0 0]]
              precision    recall  f1-score   support

         Bug       0.36      0.40      0.38        10
        Dark       0.00      0.00      0.00         7
      Dragon       0.00      0.00      0.00         6
    Electric       0.24      0.44      0.31         9
       Fairy       0.00   

x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
x:\programs\python\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
